server :
  address : localhost
  port : 12030

spring :
  profiles :
    active : local
    include: console-logging, file-logging

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/Meeting4u?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: meeting4u!

  jwt:
    secret: JwtToken

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true #entity -> db에 적용
    hibernate.ddl-auto: validate #valdate : db와 entity가 제대로 매핑 돼 있는지 확인
    database: mysql
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  logging:
    level:
      org.springframework: INFO
      org.springframework.web: DEBUG